name: Cloudman Pipeline
on:
  push:
    paths: ['**/manifest.json']

jobs:
  infrastructure:
    uses: CloudManPro/cloudman-core/.github/workflows/engine.yml@main
    with:
      aws_region: "us-east-1"
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}